# Generated by Django 5.1.1 on 2024-10-19 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('course', models.CharField(choices=[('Bi.P.C', 'Bi.P.C'), ('M.P.C', 'M.P.C'), ('M.E.C', 'M.E.C'), ('C.E.C', 'C.E.C')], max_length=10)),
                ('dob', models.DateField(blank=True, default=None, null=True)),
                ('father_name', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('mother_name', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('phone_number', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('hobbies', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('perentage_marks', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coaching', models.CharField(choices=[('AP CET', 'AP CET'), ('IIT', 'IIT'), ('AIEEE', 'AIEEE')], max_length=10)),
                ('hostel_day', models.CharField(choices=[('Day Scholer', 'Day Scholer'), ('Hostel', 'Hostel')], max_length=15)),
                ('address', models.CharField(blank=True, default=None, max_length=250, null=True)),
                ('about_yourself', models.CharField(blank=True, default=None, max_length=500, null=True)),
            ],
        ),
    ]
