# Generated by Django 5.1.1 on 2024-10-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_List', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
