# Generated by Django 5.1.1 on 2024-10-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_List', '0002_student_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
