# Generated by Django 5.1.1 on 2024-10-20 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student_List', '0004_alter_student_perentage_marks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='perentage_marks',
            new_name='percentage_marks',
        ),
    ]
