# Generated by Django 5.1.1 on 2024-10-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_List', '0005_rename_perentage_marks_student_percentage_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True)),
                ('subject', models.CharField(max_length=30)),
                ('messages', models.CharField(max_length=100)),
            ],
        ),
    ]
