# Generated by Django 5.1.1 on 2024-10-20 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student_List', '0006_contact_us'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('years_of_experience', models.IntegerField()),
                ('qualification', models.CharField(max_length=100)),
                ('teaching_experience', models.BooleanField()),
                ('key_requirements', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('pay_range', models.CharField(max_length=50)),
                ('schedule', models.CharField(max_length=50)),
                ('note', models.TextField()),
                ('contact', models.CharField(max_length=20)),
                ('work_location', models.CharField(max_length=100)),
                ('how_to_apply', models.TextField()),
            ],
        ),
    ]
