# Generated by Django 5.1.1 on 2024-10-20 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student_List', '0007_jobopening'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobopening',
            name='how_to_apply',
        ),
    ]
